Making hrp2-torque-control and sot-torque-control independent.
stack-of-tasks/sot-torque-control pull request #22
Opened 2017-06-10 22:41 UTC by olivier-stasse

This new pull request is rebased on latest modification of sot-v3.

2017-06-14 20:57 UTC, andreadelprete requested changes
This is just a partial review I did up to inverse-dynamics-balance-controller.cpp (excluded)

2017-06-14 20:57 UTC, andreadelprete commented on src/common-py.cpp
> +    .def("get_joint_limits_from_id",&RobotUtil::cp_get_joint_limits_from_id)
Why is the method called ```cp_get_joint_limits_from_id```? I'm referring to the initial ```cp```.

2017-06-14 20:57 UTC, andreadelprete commented on src/control-manager.cpp
> +	std::string localName("control-manager-robot");
I know I already said it, but just as a reminder, this string "control-manager-robot" should be taken as an input parameter of the init command.

2017-06-14 20:57 UTC, andreadelprete commented on src/free-flyer-locator.cpp
> +          assert(m_model->existFrame(m_robot_util->m_foot_util.m_Left_Foot_Frame_Name));
Are you sure that ```m_Left_Foot_Frame_Name``` has been set at this point?

2017-06-14 20:57 UTC, andreadelprete commented on src/free-flyer-locator.cpp
> +                          m_q_sot.head(6));
I see no reason to change that...

2017-06-15 10:07 UTC, andreadelprete requested changes
I finished the review I started yesterday!

2017-06-15 10:07 UTC, andreadelprete commented on src/position-controller.cpp
> +						    "Size of the state vector (double)")));
This comment is a bit ambiguous. I suggest replacing "size of the state vector" with something like "number of controlled joints".

2017-06-15 10:07 UTC, andreadelprete commented on unitTesting/test_se3_trajectory_generator.py
> +se3tg.recompute(10)
I think you should first initialize the entity, and then call ```recompute``` on the output signal (and not directly on the entity).

2017-06-15 10:07 UTC, andreadelprete commented on unitTesting/unit_test_inverse_dynamics_balance_controller.py
> +rfRefPos=zeros(12)
The first 9 values of this vector represent a rotation matrix, so you should not set all elements to zero.

2017-06-15 12:53 UTC, olivier-stasse commented on src/common-py.cpp
> +    .def("get_joint_limits_from_id",&RobotUtil::cp_get_joint_limits_from_id)
cp is for copy and avoid sending back reference

2017-06-15 13:38 UTC, olivier-stasse commented on src/free-flyer-locator.cpp
> +          assert(m_model->existFrame(m_robot_util->m_foot_util.m_Left_Foot_Frame_Name));
It should be...

2017-06-15 13:51 UTC, olivier-stasse commented on unitTesting/test_se3_trajectory_generator.py
> +se3tg.recompute(10)
Fix in commit 2b13647b1

2017-06-15 13:52 UTC, olivier-stasse commented on unitTesting/unit_test_inverse_dynamics_balance_controller.py
> +rfRefPos=zeros(12)
Fix in 2009b21a

2017-09-22 09:07 UTC, closed without merging