Topic/traj gen
stack-of-tasks/sot-torque-control pull request #39
Opened 2017-11-07 17:26 UTC by proyan

*Adds playSpline to load splines from a file
*Adds required dependency to [stack-of-tasks/parametric-curves](https://github.com/stack-of-tasks/parametric-curves) package
* Moves nd-TrajectoryGenerator base trajectories out of sot-torque-control to parametric-curves

*** Everything except Text-File Trajectory Generator tested on simulation.**
TODO:
Currently, it disables constant-acceleration and triangle-trajectory (still to be impemented in parametric-curves)

2017-11-08 13:50 UTC, proyan commented
* constant-acceleration trajectory tested and activated in last commit

2017-11-08 16:04 UTC, andreadelprete requested changes
Everything looks fine to me except the fact that you have a single variable m_infiniteTime, whereas I think you should have one of these variables for each axis.

2017-11-09 17:19 UTC, proyan commented on scripts/python_commands.txt
> +robot.com_traj_gen.playSpline("/local/rbudhira/git/proyan/sot-torque-control/scripts/spline1.out")
Done.

2017-11-09 17:19 UTC, proyan commented on scripts/spline_trajectory_maker.py
> +CONTACT_SEQUENCE_WHOLEBODY_FILE="/local/rbudhira/git/jcarpent/reachability/wb_contact_sequence/contact_sequence_trajectory.xml"
I made them relative to the package.

2017-11-09 17:19 UTC, proyan commented on include/sot/torque_control/nd-trajectory-generator.hh
> +        bool              m_infiniteTime;    /// true if trajectory is to go on forever
I think a better way might be setting infinite as the tmax for the trajectories. I'll do that.

2017-11-22 10:19 UTC, merged